### ISSUE TITLE
"clear screen" button

### ISSUE THREAD

**Issue by batdevis** [DoctorLai/LogoTurtle#12]
Hi, great work, my 6 years old son loves it.

Have you planned to make a "clear screen" button?

I know it is possible with the `CS` command, but it would be more intuitive for a child.

**Comment by DoctorLai** [comment]
Thank you for suggestion.. good idea.. I 'll add it whenever I have some time.

**Comment by DoctorLai** [comment]
@batdevis   added "CS" Button in v0.17 - but requires Google to review it - should be updated in the following days.

![Uploading image.png…]()

**Comment by batdevis** [comment]
@DoctorLai you're great!

And this button is a great explanation for my son about the open-source world.

Thank you
